apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-gw41
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0056-tenant/tkrw-pr712-0075-0056-app/devfile-sample-gw41@sha256:9140100ac16d61a4b56aa74d6ddb5896ec244eb209e7fefd67482fe3e7baa700
        name: my-nodejs
        resources: {}
status: {}
